name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
    - name: Rust Cargo Deb Package Build (armv7, Debian)
      # You may pin to the exact commit or the version.
      # uses: ebbflow-io/cargo-deb-armv7-debian@bf93e5bcbd610ef995cc510874832080cb09ae77
      uses: ebbflow-io/cargo-deb-armv7-debian@1.0
    - name: Rust Cargo Deb Package Build (amd64, Ubuntu)
      # You may pin to the exact commit or the version.
      # uses: ebbflow-io/cargo-deb-amd64-ubuntu@10535fdef274ceb3c64916b052d0d59d94e97455
      uses: ebbflow-io/cargo-deb-amd64-ubuntu@1.0
